#permalink: /:categories/:year-:month-:day/:title
permalink: /blog/:year-:month-:day/:title

title: Nicholas Studt
production_url: http://nicholasstudt.com

#paginate: 3 //the number of post per page

author : 
 name : Nihcolas Studt
 email : nicholas@nicholasstudt.com
 twitter : NicholasStudt
 linkedin : nicholasstudt
 facebook: nicholas.studt

exclude: README.md
